import moment from "moment";
import { BioQuantity } from "../../../../models/BioQuantities";

export const mockData: BioQuantity[] = [
  {
    id: 1,
    name: "Test bio quantity 0",
    isValid: true,
    link: "/somewhere",
    userId: 1,
    organismId: 2,
    unitId: 123,
    timeTo: moment.utc().toISOString(),
    timeFrom: moment.utc().add(1, "hour").toISOString(),
    valueTo: 2,
    valueFrom: 33,
    valueStep: 3,
  },
  {
    id: 2,
    name: "Test bio quantity 1",
    isValid: true,
    link: "/somewhere",
    userId: 1,
    organismId: 2,
    unitId: 123,
    timeTo: moment.utc().toISOString(),
    timeFrom: moment.utc().add(1, "hour").toISOString(),
    valueTo: 2,
    valueFrom: 33,
    valueStep: 3,
  },
  {
    id: 3,
    name: "Test bio quantity 2",
    isValid: true,
    link: "/somewhere",
    userId: 1,
    organismId: 2,
    unitId: 123,
    timeTo: moment.utc().toISOString(),
    timeFrom: moment.utc().add(1, "hour").toISOString(),
    valueTo: 2,
    valueFrom: 33,
    valueStep: 3,
  },
  {
    id: 4,
    name: "Testing quantity",
    isValid: true,
    link: "/somewhere",
    userId: 1,
    organismId: 2,
    unitId: 123,
    timeTo: moment.utc().toISOString(),
    timeFrom: moment.utc().add(1, "hour").toISOString(),
    valueTo: 2,
    valueFrom: 33,
    valueStep: 3,
  },
  {
    id: 5,
    name: "Lorem ipsum",
    isValid: true,
    link: "/somewhere",
    userId: 1,
    organismId: 2,
    unitId: 123,
    timeTo: moment.utc().toISOString(),
    timeFrom: moment.utc().add(1, "hour").toISOString(),
    valueTo: 2,
    valueFrom: 33,
    valueStep: 3,
  },
  {
    id: 6,
    name: "Dolor sit amet",
    isValid: true,
    link: "/somewhere",
    userId: 1,
    organismId: 2,
    unitId: 123,
    timeTo: moment.utc().toISOString(),
    timeFrom: moment.utc().add(1, "hour").toISOString(),
    valueTo: 2,
    valueFrom: 33,
    valueStep: 3,
  },
  {
    id: 7,
    name: "Hello world quantity",
    isValid: true,
    link: "/somewhere",
    userId: 1,
    organismId: 2,
    unitId: 123,
    timeTo: moment.utc().toISOString(),
    timeFrom: moment.utc().add(1, "hour").toISOString(),
    valueTo: 2,
    valueFrom: 33,
    valueStep: 3,
  },
  {
    id: 8,
    name: "Quantity hello world",
    isValid: true,
    link: "/somewhere",
    userId: 1,
    organismId: 2,
    unitId: 123,
    timeTo: moment.utc().toISOString(),
    timeFrom: moment.utc().add(1, "hour").toISOString(),
    valueTo: 2,
    valueFrom: 33,
    valueStep: 3,
  },
];
